
#================================================================
#===
#===               THIS IS NOT PART OF THE PACKAGE
#===
#=== This file contains some examples of how to include sections 
#=== that are needed but not included as part of the package.
#===
#===                   DO NOT COPY IT BLINDLY!!
#===
#================================================================

#================
#=== Input texts
#================
input_text:
  notifications_user1_name:
    min: 0
    max: 20

  notifications_user2_name:
    min: 0
    max: 20
    
    
#============
#=== Sensors
#============
sensor:
  #==================
  #=== Time and Date 
  #==================
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

  #==================================================
  #=== DarkSky (See the readme for more information)
  #==================================================
  - platform: darksky
    api_key: !secret darksky_api_key
    forecast:
      - 0
    monitored_conditions:
      - temperature_high           
      - minutely_summary 


  #=================================================================
  #=== Create the text and icon for Weather Outlook on the Cycle Start time
  #=================================================================
  - platform: template
    sensors:
      irrigation_weather_outlook:
        friendly_name: "Irrigation weather outlook"
        icon_template: >-
            {% if is_state("sensor.dark_sky_icon_1d","clear-day") %} mdi:weather-sunny 
            {% elif is_state("sensor.dark_sky_icon_1d","clear-night") %} mdi:weather-night 
            {% elif is_state("sensor.dark_sky_icon_1d","rain") %} mdi:weather-rainy
            {% elif is_state("sensor.dark_sky_icon_1d","snow") %} mdi:weather-snowy
            {% elif is_state("sensor.dark_sky_icon_1d","fog") %} mdi:weather-fog
            {% elif is_state("sensor.dark_sky_icon_1d","sleet") %} mdi:weather-partly-snowy-rainy
            {% elif is_state("sensor.dark_sky_icon_1d","wind") %} mdi:weather-windy
            {% elif is_state("sensor.dark_sky_icon_1d","cloudy") %} mdi:weather-cloudy
            {% elif is_state("sensor.dark_sky_icon_1d","partly-cloudy-day") %} mdi:weather-partly-cloudy
            {% elif is_state("sensor.dark_sky_icon_1d","partly-cloudy-night") %} mdi:weather-night-partly-cloudy
            {% elif is_state("sensor.dark_sky_icon_1d","hail") %} mdi:weather-hail
            {% elif is_state("sensor.dark_sky_icon_1d","lightning") %} mdi:weather-lightning
            {% elif is_state("sensor.dark_sky_icon_1d","thunderstorm") %} mdi:weather-lightning-rainy
            {% endif %}
        value_template: >+ # "keep": keep the line feed, keep trailing blank lines.
            {{states('sensor.dark_sky_summary_1d')}}
             High of {{ states('sensor.dark_sky_daytime_high_temperature_1d') }}°C 
             Low of {{ states('sensor.dark_sky_overnight_low_temperature_1d') }}°C

   - platform: darksky
     api_key: !secret dark_sky_key
     units: uk2
     forecast:
       - 0 # Today only
       - 1 # Tommorrow
     hourly_forecast:
       - 0
       - 1
     monitored_conditions:
       - temperature_high
       - temperature_low
       - precip_intensity
       - wind_speed
       - temperature
       - humidity  
  
  #=======================================================
  #=== SmartWeather (See the readme for more information)
  #=======================================================
  - platform: rest
    resource: !secret smartweather_resource_1
    name: smartweather_1
    value_template: >
      {{ value_json.station_id }}
    json_attributes:
      - status
      - station_units
      - obs    
    scan_interval:
      minutes: NUMBER OF SECONDS
      
#=== Smartweather secret
smartweather_resource_1: http://swd.weatherflow.com/swd/rest/observations/station/STATION_NUMBER?api_key=API_KEY

