# lovelace_gen

#======================
#=== RAINFALL SETTINGS
#======================
type: entities
entities:

  - type: custom:hui-element
    card_type: vertical-stack
    cards:

      #=== GENERAL RAINFALL SETTINGS
      - type: custom:button-card  
        show_icon: false
        name: GENERAL RAINFALL SETTINGS
        tap_action:
          action: none

        #=== ANCHOR STYLES FOR ALL HEADINGS ON THE PAGE
        styles: &title_style
          card:
            - color: var(--secondary-text-color)
            - border-radius: 0em
            - background: none
            - padding-top: 0em
            - padding-bottom: 0em
            - padding-left: 0.5em
            - font-family: >
                [[[
                  return states['input_text.irrigation_ui_font_family'].state
                ]]]
            - font-size: 18px
          name:
            - justify-self: start
            - border-left: 3px solid var(--accent-color)
            - padding-left: 0.5em

      #=== NUMBER OF DAYS HISTORY
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_days_of_rainfall_history_used
            name: Number of days history to use
            label: (0 to 4) If zero only rainfall today is used
            round: 0

      #=== RAINFALL THRESHOLD
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_threshold
            name: Rainfall threshold
            label: If this threshold is reached no watering takes place

      #=== IGNORE SCHEDULES IF RAINING
      - !include
        - ../item_settings_check_box_with_entity_icon.yaml
        - entity: input_boolean.irrigation_ignore_schedule_if_raining
          columns: 1
          on_icon: mdi:calendar-check-outline
          off_icon: mdi:calendar-remove-outline

      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------

      - type: custom:hui-element
        card_type: horizontal-stack
        cards:

          #=== RAINFALL INCLUDED IN CALCULATIONS
          - type: custom:button-card  
            show_icon: false
            name: RAINFALL INCLUDED IN CALCULATIONS
            tap_action:
              action: none
            styles: *title_style

          #=== EDIT BUTTON FOR RAINFALL INCLUDED IN CALCULATIONS
          - type: custom:button-card
            icon: mdi:square-edit-outline
            styles:
              card:
                - width: 4em
                - padding-right: 0.5em

            #=== ALLOW EDITING OF PERCENTAGES
            tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  title: Rainfall Included in Calculations
                  content:
                    type: entities
                    entities:
                      - entity: input_boolean.irrigation_rainfall_use_rolling_values

                      #=== Rolling values
                      - type: custom:hui-element
                        card_type: conditional
                        conditions:
                          - entity: input_boolean.irrigation_rainfall_use_rolling_values
                            state: 'on'
                        card:
                          type: entities
                          entities:
                            - entity: input_number.irrigation_rainfall_percentage_1
                              name: 24 to 48 hours ago
                            - entity: input_number.irrigation_rainfall_percentage_2
                              name: 48 to 72 hours ago
                            - entity: input_number.irrigation_rainfall_percentage_3
                              name: 72 to 96 hours ago
                            - entity: input_number.irrigation_rainfall_percentage_4
                              name: 96 to 120 hours ago

                      #=== Absolute day values
                      - type: custom:hui-element
                        card_type: conditional
                        conditions:
                          - entity: input_boolean.irrigation_rainfall_use_rolling_values
                            state: 'off'
                        card:
                          type: entities
                          entities:
                            - entity: input_number.irrigation_rainfall_percentage_1
                              name: Yesterday
                            - entity: input_number.irrigation_rainfall_percentage_2
                              name: Two days ago
                            - entity: input_number.irrigation_rainfall_percentage_3
                              name: Three days ago
                            - entity: input_number.irrigation_rainfall_percentage_4
                              name: Four days ago

                    card_mod:
                      style: >
                        ha-card {
                          font-family: {% raw %}{{ states('input_text.irrigation_ui_font_family') }}{% endraw %};
                          }
                  #=== Style needed for pop-up title
                  style:
                    $: |
                      .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
                          font-family: {% raw %}{{ states('input_text.irrigation_ui_font_family') }}{% endraw %};
                        }

      #=== 24 to 48 hours ago
      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_1
            name: 24 to 48 hours ago
            rolling: 'on'
            padding: 0.3em 0em 0em 0em

      #=== 48 to 72 hours ago
      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_2
            name: 48 to 72 hours ago
            rolling: 'on'

      #=== 72 to 96 hours ago
      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_3
            name: 72 to 96 hours ago
            rolling: 'on'

      #=== 96 to 120 hours ago
      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_4
            name: 96 to 120 hours ago
            rolling: 'on'

      #=== YESTERDAY
      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_1
            name: Yesterday
            rolling: 'off'
            padding: 0.3em 0em 0em 0em

      #=== TWO DAYS AGO
      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_2
            name: Two days ago
            rolling: 'off'

      #=== THREE DAYS AGO
      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_3
            name: Three days ago
            rolling: 'off'

      #=== FOUR DAYS AGO
      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_4
            name: Four days ago
            rolling: 'off'

      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------

      #=== RAINFALL DATA
      - type: custom:button-card  
        show_icon: false
        name: RAINFALL DATA
        tap_action:
          action: none
        styles: *title_style

      #=== MULTIPLIER USED IN CALCULATIONS
      - !include
          - ../item_settings_multiplier_line.yaml
          - entity: input_number.irrigation_rainfall_multiplier
            name: "Current Multiplier ( ℹ️ )"
            label: Calculated based on rainfall and threshold

      #=== Rolling values
      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: sensor.irrigation_sensor_rainfall_last_twenty_four_hours
            name: Last 24 hours
            rolling: 'on'
            round: 1
            padding: 0.3em 0em 0em 0em

      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: sensor.irrigation_sensor_rainfall_between_24_and_48_hours_ago
            name: 24 to 48 hours ago
            rolling: 'on'
            round: 1

      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: sensor.irrigation_sensor_rainfall_between_48_and_72_hours_ago
            name: 48 to 72 hours ago
            rolling: 'on'
            round: 1

      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: sensor.irrigation_sensor_rainfall_between_72_and_96_hours_ago
            name: 72 to 96 hours ago
            rolling: 'on'
            round: 1

      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: sensor.irrigation_sensor_rainfall_between_96_and_120_hours_ago
            name: 96 to 120 hours ago
            rolling: 'on'
            round: 1
            padding: 0em 0em 0.3em 0em


      #=== Absolute daily values
      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: sensor.irrigation_sensor_rainfall_today
            name: Rainfall today
            rolling: 'off'
            round: 1
            padding: 0.3em 0em 0em 0em

      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: sensor.irrigation_sensor_rainfall_yesterday
            name: Yesterday
            rolling: 'off'
            round: 1

      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: input_number.irrigation_rainfall_2
            name: Two days ago
            rolling: 'off'
            round: 1

      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: input_number.irrigation_rainfall_3
            name: Three days ago
            rolling: 'off'
            round: 1

      - !include
          - ../rainfall/item_settings_rainfall_line.yaml
          - entity: input_number.irrigation_rainfall_4
            name: Four days ago
            rolling: 'off'
            round: 1
            padding: 0em 0em 0.3em 0em



      # #===
      # #=== USING ROLLING VALUES
      # #===

      # #=== LAST 24 HOURS
      # - type: conditional
      #   conditions:
      #     - entity: input_boolean.irrigation_rainfall_use_rolling_values
      #       state: 'on'
      #   card:
      #     !include
      #       - ../item_settings_line.yaml
      #       - entity: sensor.irrigation_sensor_rainfall_last_twenty_four_hours
      #         name: Last 24 hours
      #         icon: mdi:weather-rainy
      #         round: 1
      #         tap_action: none

      # #=== 24 TO 48 HOURS AGO
      # - type: conditional
      #   conditions:
      #     - entity: input_boolean.irrigation_rainfall_use_rolling_values
      #       state: 'on'
      #   card:
      #     !include
      #       - ../item_settings_line.yaml
      #       - entity: sensor.irrigation_sensor_rainfall_between_24_and_48_hours_ago
      #         name: 24 to 48 hours ago
      #         icon: mdi:weather-rainy
      #         round: 1
      #         tap_action: none

      # #=== 48 TO 72 HOURS AGO
      # - type: conditional
      #   conditions:
      #     - entity: input_boolean.irrigation_rainfall_use_rolling_values
      #       state: 'on'
      #   card:
      #     !include
      #       - ../item_settings_line.yaml
      #       - entity: sensor.irrigation_sensor_rainfall_between_48_and_72_hours_ago
      #         name: 48 to 72 hours ago
      #         icon: mdi:weather-rainy
      #         round: 1
      #         tap_action: none

      # #=== 72 TO 96 HOURS AGO
      # - type: conditional
      #   conditions:
      #     - entity: input_boolean.irrigation_rainfall_use_rolling_values
      #       state: 'on'
      #   card:
      #     !include
      #       - ../item_settings_line.yaml
      #       - entity: sensor.irrigation_sensor_rainfall_between_72_and_96_hours_ago
      #         name: 72 to 96 hours ago
      #         icon: mdi:weather-rainy
      #         round: 1
      #         tap_action: none

      # #=== 96 TO 120 HOURS AGO
      # - type: conditional
      #   conditions:
      #     - entity: input_boolean.irrigation_rainfall_use_rolling_values
      #       state: 'on'
      #   card:
      #     !include
      #       - ../item_settings_line.yaml
      #       - entity: sensor.irrigation_sensor_rainfall_between_96_and_120_hours_ago
      #         name: 96 to 120 hours ago
      #         icon: mdi:weather-rainy
      #         round: 1
      #         tap_action: none


      # #===
      # #=== USING DAILY VALUES
      # #===

      # #=== RAINFALL TODAY
      # - type: conditional
      #   conditions:
      #     - entity: input_boolean.irrigation_rainfall_use_rolling_values
      #       state: 'off'
      #   card:
      #     !include
      #       - ../item_settings_line.yaml
      #       - entity: sensor.irrigation_sensor_rainfall_today
      #         name: Rainfall Today
      #         icon: mdi:weather-rainy
      #         round: 1
      #         tap_action: none

      # #=== RAINFALL YESTERDAY
      # - type: conditional
      #   conditions:
      #     - entity: input_boolean.irrigation_rainfall_use_rolling_values
      #       state: 'off'
      #   card:
      #     !include
      #       - ../item_settings_line.yaml
      #       - entity: sensor.irrigation_sensor_rainfall_yesterday
      #         name: Yesterday
      #         icon: mdi:weather-rainy
      #         round: 1
      #         tap_action: none
      #         display_condition: "[[[ return states['input_number.irrigation_days_of_rainfall_history_used'].state < 1 ? 'none' : 'unset' ]]]"

      # #=== RAINFALL TWO DAYS AGO
      # - type: conditional
      #   conditions:
      #     - entity: input_boolean.irrigation_rainfall_use_rolling_values
      #       state: 'off'
      #   card:
      #     !include
      #       - ../item_settings_line.yaml
      #       - entity: input_number.irrigation_rainfall_2
      #         name: Two days ago
      #         round: 1
      #         tap_action: none
      #         display_condition: "[[[ return states['input_number.irrigation_days_of_rainfall_history_used'].state < 2 ? 'none' : 'unset' ]]]"

      # #=== RAINFALL THREE DAYS AGO
      # - type: conditional
      #   conditions:
      #     - entity: input_boolean.irrigation_rainfall_use_rolling_values
      #       state: 'off'
      #   card:
      #     !include
      #       - ../item_settings_line.yaml
      #       - entity: input_number.irrigation_rainfall_3
      #         name: Three days ago
      #         round: 1
      #         tap_action: none
      #         display_condition: "[[[ return states['input_number.irrigation_days_of_rainfall_history_used'].state < 3 ? 'none' : 'unset' ]]]"

      # #=== RAINFALL FOUR DAYS AGO
      # - type: conditional
      #   conditions:
      #     - entity: input_boolean.irrigation_rainfall_use_rolling_values
      #       state: 'off'
      #   card:
      #     !include
      #       - ../item_settings_line.yaml
      #       - entity: input_number.irrigation_rainfall_4
      #         name: Four days ago
      #         round: 1
      #         tap_action: none
      #         display_condition: "[[[ return states['input_number.irrigation_days_of_rainfall_history_used'].state < 4 ? 'none' : 'unset' ]]]"
      #         padding: 0em 0em 0.3em 0em

      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------

      #=== FORECAST RAIN VS. ACTUAL RAIN
      - type: custom:button-card  
        show_icon: false
        name:  RAINFALL - <font color=IndianRed>Forecast</font> vs. <font color=SteelBlue>Actual</font>
        tap_action:
          action: none
        styles: *title_style

      #=== FORECAST VS. ACTUAL RIAN GRAPH
      - !include item_settings_rainfall_graph.yaml

card_mod:
  style: >
    ha-card {
      box-shadow: none;
    }
