
#===================
#=== Input Booleans
#===================
input_boolean:

  #======================
  #=== Show Cycles in UI
  #======================
  irrigation_ui_show_cycle1:
    name: Show Cycle 1

  irrigation_ui_show_cycle2:
    name: Show Cycle 2

  irrigation_ui_show_cycle3:
    name: Show Cycle 3

  #========================
  #=== Show Settings in UI
  #========================
  irrigation_ui_show_general_settings:
    name: General

  irrigation_ui_show_rainfall_settings:
    name: Rainfall

  irrigation_ui_show_temperature_settings:
    name: Temperature

  #====================================
  #=== Show History and Last Run in UI
  #====================================
  irrigation_ui_show_last_run_details:
    name: Last Run

  irrigation_ui_show_status_history:
    name: Status History


#============
#=== Sensors
#============
sensor:
  - platform: template
    sensors:
      irrigation_ui_selected_cycle:
        value_template: >
          {% if is_state('input_boolean.irrigation_ui_show_cycle1', 'on') %}   
            cycle1
          {% elif is_state('input_boolean.irrigation_ui_show_cycle2', 'on') %}   
            cycle2
          {% elif is_state('input_boolean.irrigation_ui_show_cycle3', 'on') %}   
            cycle3
          {% else %}
            no cycle selected
          {% endif %}

      irrigation_ui_selected_settings:
        value_template: >
          {% if is_state('input_boolean.irrigation_ui_show_general_settings', 'on') %}   
            general
          {% elif is_state('input_boolean.irrigation_ui_show_rainfall_settings', 'on') %}   
            rainfall
          {% elif is_state('input_boolean.irrigation_ui_show_temperature_settings', 'on') %}   
            temperature
          {% else %}
            no settings selected
          {% endif %}


#================
#=== Automations
#================
automation:

  #=============================
  #=== SECTION HEADER SELECTION
  #=============================
  #=====================
  # Show Selected Cycle
  #=====================
  - alias: Irrigation UI Show Selected Cycle
    mode: queued
    trigger:
      - platform: state
        entity_id:
          - input_boolean.irrigation_ui_show_cycle1
          - input_boolean.irrigation_ui_show_cycle2
          - input_boolean.irrigation_ui_show_cycle3
        to: 'on'

    action:
      - service: input_boolean.turn_off
        data_template:
          entity_id: >
            {% if 'cycle1' in trigger.entity_id %}   
              input_boolean.irrigation_ui_show_cycle2,
              input_boolean.irrigation_ui_show_cycle3
            {% elif 'cycle2' in trigger.entity_id %}
              input_boolean.irrigation_ui_show_cycle1,
              input_boolean.irrigation_ui_show_cycle3
            {% else %}
              input_boolean.irrigation_ui_show_cycle1,
              input_boolean.irrigation_ui_show_cycle2
            {% endif %}


  #===========================
  # Prevent No Selected Cycle
  #===========================
  - alias: Irrigation UI Prevent No Selected Cycle
    mode: queued
    trigger:
      - platform: state
        entity_id:
          - input_boolean.irrigation_ui_show_cycle1
          - input_boolean.irrigation_ui_show_cycle2
          - input_boolean.irrigation_ui_show_cycle3
        to: 'off'

    condition:
      - condition: state
        entity_id: input_boolean.irrigation_ui_show_cycle1
        state: 'off'

      - condition: state
        entity_id: input_boolean.irrigation_ui_show_cycle2
        state: 'off'

      - condition: state
        entity_id: input_boolean.irrigation_ui_show_cycle3
        state: 'off'

    action:
      - service: input_boolean.turn_on
        data_template:
          entity_id: >
            {{ trigger.entity_id }}


  #========================
  # Show Selected Settings
  #========================
  - alias: Irrigation UI Show Selected Settings
    trigger:
      - platform: state
        entity_id:
          - input_boolean.irrigation_ui_show_general_settings
          - input_boolean.irrigation_ui_show_rainfall_settings
          - input_boolean.irrigation_ui_show_temperature_settings
        to: 'on'

    action:
      - service: input_boolean.turn_off
        data_template:
          entity_id: >
            {% if 'general' in trigger.entity_id %}   
              input_boolean.irrigation_ui_show_rainfall_settings,
              input_boolean.irrigation_ui_show_temperature_settings
            {% elif 'rainfall' in trigger.entity_id %}
              input_boolean.irrigation_ui_show_general_settings,
              input_boolean.irrigation_ui_show_temperature_settings
            {% else %}
              input_boolean.irrigation_ui_show_general_settings,
              input_boolean.irrigation_ui_show_rainfall_settings
            {% endif %}


  #==============================
  # Prevent No Selected Settings
  #==============================
  - alias: Irrigation UI Prevent No Selected Settings
    trigger:
      - platform: state
        entity_id:
          - input_boolean.irrigation_ui_show_general_settings
          - input_boolean.irrigation_ui_show_rainfall_settings
          - input_boolean.irrigation_ui_show_temperature_settings
        to: 'off'

    condition:
      - condition: state
        entity_id: input_boolean.irrigation_ui_show_general_settings
        state: 'off'

      - condition: state
        entity_id: input_boolean.irrigation_ui_show_rainfall_settings
        state: 'off'

      - condition: state
        entity_id: input_boolean.irrigation_ui_show_temperature_settings
        state: 'off'

    action:
      - service: input_boolean.turn_on
        data_template:
          entity_id: >
            {{ trigger.entity_id }}


  #=============================================================
  #=== Show relevent Settings page when adjustment is turned on
  #=============================================================
  - alias: Irrigation UI Show Weather Adjust Settings
    mode: queued
    trigger:
      - platform: state
        entity_id: 
          - input_boolean.irrigation_cycle1_adjust_for_rainfall
          - input_boolean.irrigation_cycle2_adjust_for_rainfall
          - input_boolean.irrigation_cycle1_adjust_for_temperature
          - input_boolean.irrigation_cycle2_adjust_for_temperature
        to: 'on'

    action:
      - service: input_boolean.turn_on
        data_template:
          entity_id: >
            {% if 'rainfall' in trigger.entity_id %}
              input_boolean.irrigation_ui_show_rainfall_settings
            {% else %}
              input_boolean.irrigation_ui_show_temperature_settings
            {% endif %}

  #=== END OF SECTION HEADER SELECTION BUTTONS


  #==========================
  #=== ZONE DURATION CHANGES
  #==========================
  #==================================================
  #=== Zone Duration updated
  #=== Keep input_number slider and box synchronised
  #==================================================
  - alias: Irrigation UI Duration Synchronisation
    mode: queued
    trigger: 
      - platform: state
        entity_id:
          - input_number.irrigation_cycle1_zone1_duration
          - input_number.irrigation_cycle1_zone1_duration_box
          - input_number.irrigation_cycle1_zone2_duration
          - input_number.irrigation_cycle1_zone2_duration_box
          - input_number.irrigation_cycle1_zone3_duration
          - input_number.irrigation_cycle1_zone3_duration_box
          - input_number.irrigation_cycle1_zone4_duration
          - input_number.irrigation_cycle1_zone4_duration_box
          - input_number.irrigation_cycle1_zone5_duration
          - input_number.irrigation_cycle1_zone5_duration_box
          - input_number.irrigation_cycle1_zone6_duration
          - input_number.irrigation_cycle1_zone6_duration_box
          - input_number.irrigation_cycle1_zone7_duration
          - input_number.irrigation_cycle1_zone7_duration_box
          - input_number.irrigation_cycle1_zone8_duration
          - input_number.irrigation_cycle1_zone8_duration_box
          - input_number.irrigation_cycle1_zone9_duration
          - input_number.irrigation_cycle1_zone9_duration_box
          - input_number.irrigation_cycle1_zone10_duration
          - input_number.irrigation_cycle1_zone10_duration_box
          - input_number.irrigation_cycle1_zone11_duration
          - input_number.irrigation_cycle1_zone11_duration_box
          - input_number.irrigation_cycle1_zone12_duration
          - input_number.irrigation_cycle1_zone12_duration_box
          - input_number.irrigation_cycle1_zone13_duration
          - input_number.irrigation_cycle1_zone13_duration_box
          - input_number.irrigation_cycle1_zone14_duration
          - input_number.irrigation_cycle1_zone14_duration_box
          - input_number.irrigation_cycle1_zone15_duration
          - input_number.irrigation_cycle1_zone15_duration_box
          - input_number.irrigation_cycle1_zone16_duration
          - input_number.irrigation_cycle1_zone16_duration_box

          - input_number.irrigation_cycle2_zone1_duration
          - input_number.irrigation_cycle2_zone1_duration_box
          - input_number.irrigation_cycle2_zone2_duration
          - input_number.irrigation_cycle2_zone2_duration_box
          - input_number.irrigation_cycle2_zone3_duration
          - input_number.irrigation_cycle2_zone3_duration_box
          - input_number.irrigation_cycle2_zone4_duration
          - input_number.irrigation_cycle2_zone4_duration_box
          - input_number.irrigation_cycle2_zone5_duration
          - input_number.irrigation_cycle2_zone5_duration_box
          - input_number.irrigation_cycle2_zone6_duration
          - input_number.irrigation_cycle2_zone6_duration_box
          - input_number.irrigation_cycle2_zone7_duration
          - input_number.irrigation_cycle2_zone7_duration_box
          - input_number.irrigation_cycle2_zone8_duration
          - input_number.irrigation_cycle2_zone8_duration_box
          - input_number.irrigation_cycle2_zone9_duration
          - input_number.irrigation_cycle2_zone9_duration_box
          - input_number.irrigation_cycle2_zone10_duration
          - input_number.irrigation_cycle2_zone10_duration_box
          - input_number.irrigation_cycle2_zone11_duration
          - input_number.irrigation_cycle2_zone11_duration_box
          - input_number.irrigation_cycle2_zone12_duration
          - input_number.irrigation_cycle2_zone12_duration_box
          - input_number.irrigation_cycle2_zone13_duration
          - input_number.irrigation_cycle2_zone13_duration_box
          - input_number.irrigation_cycle2_zone14_duration
          - input_number.irrigation_cycle2_zone14_duration_box
          - input_number.irrigation_cycle2_zone15_duration
          - input_number.irrigation_cycle2_zone15_duration_box
          - input_number.irrigation_cycle2_zone16_duration
          - input_number.irrigation_cycle2_zone16_duration_box          
          
          - input_number.irrigation_cycle3_zone1_duration
          - input_number.irrigation_cycle3_zone1_duration_box
          - input_number.irrigation_cycle3_zone2_duration
          - input_number.irrigation_cycle3_zone2_duration_box
          - input_number.irrigation_cycle3_zone3_duration
          - input_number.irrigation_cycle3_zone3_duration_box
          - input_number.irrigation_cycle3_zone4_duration
          - input_number.irrigation_cycle3_zone4_duration_box
          - input_number.irrigation_cycle3_zone5_duration
          - input_number.irrigation_cycle3_zone5_duration_box
          - input_number.irrigation_cycle3_zone6_duration
          - input_number.irrigation_cycle3_zone6_duration_box
          - input_number.irrigation_cycle3_zone7_duration
          - input_number.irrigation_cycle3_zone7_duration_box
          - input_number.irrigation_cycle3_zone8_duration
          - input_number.irrigation_cycle3_zone8_duration_box
          - input_number.irrigation_cycle3_zone9_duration
          - input_number.irrigation_cycle3_zone9_duration_box
          - input_number.irrigation_cycle3_zone10_duration
          - input_number.irrigation_cycle3_zone10_duration_box
          - input_number.irrigation_cycle3_zone11_duration
          - input_number.irrigation_cycle3_zone11_duration_box
          - input_number.irrigation_cycle3_zone12_duration
          - input_number.irrigation_cycle3_zone12_duration_box
          - input_number.irrigation_cycle3_zone13_duration
          - input_number.irrigation_cycle3_zone13_duration_box
          - input_number.irrigation_cycle3_zone14_duration
          - input_number.irrigation_cycle3_zone14_duration_box
          - input_number.irrigation_cycle3_zone15_duration
          - input_number.irrigation_cycle3_zone15_duration_box
          - input_number.irrigation_cycle3_zone16_duration
          - input_number.irrigation_cycle3_zone16_duration_box          

    action:
      #=== Keep input_number slider and box synchronised
      - service: input_number.set_value
        data_template:
          entity_id: >
            {% set cycle = 'cycle' ~ trigger.entity_id.split('cycle')[1][0] %}
            {% set zone = 'zone' ~ trigger.entity_id.split('zone')[1][0] %}
            {% if trigger.entity_id.endswith('box') %}
              input_number.irrigation_{{ cycle }}_{{ zone }}_duration
            {% else %}
              input_number.irrigation_{{ cycle }}_{{ zone }}_duration_box
            {% endif %}            
          value: >
            {% set cycle = 'cycle' ~ trigger.entity_id.split('cycle')[1][0] %}
            {% set zone = 'zone' ~ trigger.entity_id.split('zone')[1][0] %}
            {% if trigger.entity_id.endswith('box') %}
              {% set value = states('input_number.irrigation_' ~ cycle ~ '_' ~ zone ~ '_duration_box') | float %}
            {% else %}
              {% set value = states('input_number.irrigation_' ~ cycle ~ '_' ~ zone ~ '_duration') | float %}
            {% endif %}            
            {{ value }}
            
  #=== END OF ZONE DURATION CHANGES

