
#============
#=== Sensors
#============
sensor:
  - platform: template

    #=========================================================
    #=== Internal sensors that are based on the external ones
    #=== that have been user defined in the input texts.
    #===
    #=== These sensors are synchronised manually in an
    #=== automation when the external ones change
    #=========================================================
    sensors:
      irrigation_sensor_rainfall_today:
        value_template: >
          {{ states(states('input_text.irrigation_external_sensor_rainfall_today')) }}
        icon_template: mdi:weather-rainy
        unit_of_measurement: mm


      irrigation_sensor_rainfall_yesterday:
        value_template: >
          {{ states(states('input_text.irrigation_external_sensor_rainfall_yesterday')) }}
        icon_template: mdi:weather-rainy
        unit_of_measurement: mm

binary_sensor:
  - platform: template
    sensors:
      irrigation_sensor_raining_now:
        value_template: >
          {{ states(states('input_text.irrigation_external_sensor_raining_now')) }}
        icon_template: mdi:weather-pouring


#===================
#=== Input Booleans
#===================
input_boolean:
  irrigation_show_smartweather_stations:
    name: Show SmartWeather Stations
    icon: mdi:weather-rainy

  irrigation_ignore_schedule_if_raining:
    name: Ignore schedules if it is raining
    icon: mdi:calendar-remove


#================
#=== Input Texts
#================
input_text:

  #==============================
  #=== User defined sensor names
  #==============================

  #=== Sensor for rainfall today
  irrigation_external_sensor_rainfall_today:
    name: Rainfall Today Sensor
    icon: mdi:weather-pouring
    min: 0
    max: 100

  #=== Sensor for rainfall yesterday
  irrigation_external_sensor_rainfall_yesterday:
    name: Rainfall Yesterday Sensor
    icon: mdi:weather-pouring
    min: 0
    max: 100

  #=== Sensor for raining now
  irrigation_external_sensor_raining_now:
    name: Raining Now
    icon: mdi:weather-pouring
    min: 0
    max: 100
  

#==================
#=== Input_Numbers
#==================
input_number:

  #=== Rainfall Multiplier
  irrigation_rainfall_multiplier:
    name: Multiplier for rainfall
    min: 0
    max: 1
    step: 0.01
    icon: mdi:weather-rainy

  #=== Rainfall Days To Use
  irrigation_days_of_rainfall_history_used:
    name: Number of days history to use in calculations
    min: 0
    max: 4
    step: 1
    mode: box
    icon: mdi:calendar-range
    
  #=== Amount of rain before irrigation is stopped
  irrigation_rainfall_threshold:
    name: Rainfall threshold
    min: 5
    max: 30
    icon: mdi:weather-rainy
    mode: box
    unit_of_measurement: 'mm'


  #=== Rainfall History
  #=== Today and yesterday are sensors

  irrigation_rainfall_2:
    name: Two days ago
    min: 0
    max: 100
    icon: mdi:weather-rainy
    unit_of_measurement: 'mm'

  irrigation_rainfall_3:
    name: Three days ago
    min: 0
    max: 100
    icon: mdi:weather-rainy
    unit_of_measurement: 'mm'

  irrigation_rainfall_4:
    name: Four days ago
    min: 0
    max: 100
    icon: mdi:weather-rainy
    unit_of_measurement: 'mm'


  #=== Rainfall percentage to use
  irrigation_rainfall_percentage_1:
    name: Yesterday
    min: 0
    max: 100
    step: 5
    mode: box
    icon: mdi:weather-rainy
    unit_of_measurement: '%'

  irrigation_rainfall_percentage_2:
    name: Two days ago
    min: 0
    max: 100
    step: 5
    mode: box
    icon: mdi:weather-rainy
    unit_of_measurement: '%'

  irrigation_rainfall_percentage_3:
    name: Three days ago
    min: 0
    max: 100
    step: 5
    mode: box
    icon: mdi:weather-rainy
    unit_of_measurement: '%'

  irrigation_rainfall_percentage_4:
    name: Four days ago
    min: 0
    max: 100
    step: 5
    mode: box
    icon: mdi:weather-rainy
    unit_of_measurement: '%'


