
#============
#=== Sensors
#============
sensor:
  - platform: template

    #=========================================================
    #=== Internal sensors that are based on the external ones
    #=== that have been user defined in the input texts.
    #===
    #=== These sensors are synchronised manually in an
    #=== automation when the external ones change
    #=========================================================
    sensors:
      irrigation_sensor_forecast_high_temp:
        value_template: >
          {{ states(states('input_text.irrigation_external_sensor_forecast_high_temp')) }}
        icon_template: mdi-thermometer-high
        unit_of_measurement: '°C'

      irrigation_sensor_current_temp:
        value_template: >
          {{ states(states('input_text.irrigation_external_sensor_current_temp')) }}
        icon_template: mdi-thermometer-low
        unit_of_measurement: '°C'


#================
#=== Input Texts
#================
input_text:

  #==============================
  #=== User defined sensor names
  #==============================

  #=== Sensor for forecast high temperature
  irrigation_external_sensor_forecast_high_temp:
    name: Forecast High Temperature Sensor
    icon: mdi:thermometer-high
    min: 0
    max: 100

  #=== Sensor for current temperature
  irrigation_external_sensor_current_temp:
    name: Current Temperature Sensor
    icon: mdi:thermometer-lines
    min: 0
    max: 100


#==================
#=== Input_Numbers
#==================
input_number:

  #=== Temperature multiplier
  irrigation_temp_multiplier:
    name: multiplier for temperature
    min: 0
    max: 10
    step: 0.01
    icon: mdi:thermometer

  #=== Temperature Days To Use
  irrigation_days_of_temp_history_used:
    name: Number of days history to use in calculations
    min: 0
    max: 4
    step: 1
    mode: box
    icon: mdi:calendar-range

  #=== The temperature above or below which the duration is adjusted
  irrigation_temperature_baseline:
    name: Temperature baseline
    min: 20
    max: 40
    step: 1
    icon: mdi:thermometer-low
    mode: box
    unit_of_measurement: '°C'


  #=== Highest Actual Temperature Today
  irrigation_temperature_highest_actual_temp_today:
    name: Highest Actual Temperature Today
    min: 0
    max: 40
    step: 0.1
    icon: mdi:thermometer
    unit_of_measurement: '°C'
  

  #=== Highest Forecast High Temperature Today
  irrigation_temperature_highest_forecast_high_temp_today:
    name: Highest Forecast High Temperature Today
    min: 0
    max: 40
    step: 0.1
    icon: mdi:thermometer
    unit_of_measurement: '°C'
  

  #=== Temperature History
  irrigation_high_temp_1:
    name: Yesterday
    min: 0
    max: 40
    step: 0.1
    icon: mdi:thermometer-high
    unit_of_measurement: '°C'

  irrigation_high_temp_2:
    name: Two days ago
    min: 0
    max: 40
    step: 0.1
    icon: mdi:thermometer-high
    unit_of_measurement: '°C'

  irrigation_high_temp_3:
    name: Three days ago
    min: 0
    max: 40
    step: 0.1
    icon: mdi:thermometer-high
    unit_of_measurement: '°C'

  irrigation_high_temp_4:
    name: Four days ago
    min: 0
    max: 40
    step: 0.1
    icon: mdi:thermometer-high
    unit_of_measurement: '°C'


#==================
#=== Input Selects
#==================
input_select:
  irrigation_high_temp_options:
    name: High Temperature Options
    options: 
      - Use Forecast
      - Use Actual
      - Use Highest
    icon: mdi:thermometer-lines