
#================
#=== Automations
#================
automation:

  #================
  #=== Run a cycle
  #================
  - alias: Irrigation Triggered Cycle Start

    #================================================
    #=== TRIGGERS
    #================================================
    trigger:
      - platform: state
        entity_id: input_boolean.irrigation_cycle1_running
        to: 'on'
        
      - platform: state
        entity_id: input_boolean.irrigation_cycle2_running
        to: 'on'

      - platform: state
        entity_id: input_boolean.irrigation_cycle3_running
        to: 'on'

    #===============================================
    #=== ACTIONS
    #===    Update details of last run
    #===    Start the irrigation process
    #===============================================
    action:
      #=== Set previous run times for all zones to ' '
      - service: input_text.set_value
        data_template:
          entity_id: >
            {% for input_text in states.input_text if input_text.object_id.startswith('irrigation_zone') and
                                                      input_text.object_id.endswith('_previous_duration_in_seconds')  -%}
              {{ input_text.entity_id }}
              {%- if not loop.last %}, {% endif %}
            {%- endfor %}
          value: ''
      
      #=== Set previous total watering time to 'none'
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_previous_total_watering_time
          value: None

      #=== Set previous cycle total time to zero
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_previous_total_watering_time
          value: 0

      #=== Update Last Run cycle name
      - service: input_text.set_value
        data_template:
          entity_id: input_text.irrigation_previous_run_cycle_name
          value: >
            {% if trigger.entity_id == 'input_boolean.irrigation_cycle1_running' %}
              {% set cycle = 'cycle1' %}
            {% elif trigger.entity_id == 'input_boolean.irrigation_cycle2_running' %}
              {% set cycle = 'cycle2' %}
            {% else %}
              {% set cycle = 'cycle3' %}
            {% endif %}

            {{ states('input_text.irrigation_' ~ cycle ~ '_name') }}
            
      #=== Update Last Run date and time
      - service: input_text.set_value
        data_template:
          entity_id: input_text.irrigation_previous_run_date_and_time
          value: >
            {{ now().strftime("%A %d %B at %H:%M") }}
            

      #======================
      #=== START THE PROCESS
      #======================
      - service: script.irrigation_run_a_cycle
        data_template:
          cycle: >
            {% if trigger.entity_id == 'input_boolean.irrigation_cycle1_running' %}
              cycle1
            {% elif trigger.entity_id == 'input_boolean.irrigation_cycle2_running' %}
              cycle2
            {% else %}
              cycle3
            {% endif %}

